# Generated by Django 3.0.5 on 2020-05-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='city',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='state',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='zip_code',
        ),
    ]
